language: rust
rust:
  - 1.20.0
  - nightly
  - beta
  - stable
cache:
  directories:
    - dev/cmp/test-assets
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - cargo build --verbose --features async_ogg
  - cargo build --verbose --no-default-features
  - cd dev/cmp
  - cargo test --release
