[package]
name = "lewton"
version = "0.1.0"
authors = ["est31 <MTest31@outlook.com>"]
description = "Pure Rust vorbis decoder"
license = "MIT/Apache-2.0"
repository = "https://github.com/est31/lewton"
keywords = ["ogg", "vorbis", "decoder", "audio"]
documentation = "https://docs.rs/lewton/0.1.0"
readme = "README.md"

[features]
default = ["ogg", "ieee754"]
async_ogg = ["ogg", "ogg/async"]

[dependencies]
byteorder = "0.5"
ogg = { version = "~0.3.3", optional = true }
ieee754 = { version = "0.2", optional = true }

[dev-dependencies]
ogg = "~0.3.3"
openal-rs = "0.1"
time = "0.1"
rand = "0.3"
